Add more filetypes to .gitattributes
arfc/saltproc pull request #205
Opened 2024-05-24 13:48 UTC by yardasol

## Summary of changes

This PR fixed the `.gitattributes` file to correctly remove the `.m` files from the SaltProc language card. This PR also adds `.ini` ,`.h5`. and `.out` files to this list.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Required for Merging
- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly. 
- [ ] My change is a source code change
  - [ ] I have added/modified tests to cover my changes
  - [ ] I have explained why my change does not require new/modified tests
- [ ] My change is a user-facing change
  - [ ] I have recorded my changes in the changelog for the upcoming release
- [x] My change is exclusively related to the repository (e.g. GitHub actions workflows, PR/issue templates, etc.)
  - [ ] I have verified or justified that my change will work as intended.
- [ ] All new and existing tests passed.
  - [ ] CI tests pass
  - [ ] Local tests pass (including Serpent2 integration tests)
## Associated Issues and PRs

- Issue: #

## Associated Developers

- Dev: @samgdotson 

## Checklist for Reviewers

Reviewers should use [this link](https://arfc.github.io/manual/guides/pull_requests) to get to the 
Review Checklist before they begin their review.

2024-05-24 16:21 UTC, samgdotson requested changes
Looks good. Add the .mat line back in and ill approve it

2024-05-24 16:21 UTC, samgdotson commented on .gitattributes
> +*.out linguist-vendored
```suggestion
*.out linguist-vendored
*.mat linguist-vendored
```
Im pretty sure there are .mat data files, and I don’t think it hurts. But you’re correct to add ‘.m’ files.

2024-06-27 17:21 UTC, samgdotson approved these changes
Lgtm

2024-06-27 17:24 UTC, samgdotson requested changes
The change was addressed but tests are failing. This PR is definitely unrelated to failing tests but I want to make sure you’re aware of this (perhaps there’s another issue or branch that is fixing it?).

I’ll merge after this is addressed (at least verbally).

2025-04-17 20:08 UTC, yardasol commented
@samgdotson I've shoehorned in some cleanups to the workflows. Changes from #209 mean we no longer really need to cache dependencies, so I'm removing the `cache-dependencies.yml` workflow. In discussions with @katyhuff and @munkm, we decided that the automated version PRs are confusing, so I am deleting the `next-release-minor.yml` workflow. Finally, the `auto-labels.yml` workflow was a prototype idea that I'm not sure how made it into the master branch, so that is being removed as well.

2025-04-21 17:36 UTC, yardasol commented
@samgdotson bump

2025-04-24 14:41 UTC, samgdotson approved these changes
Looks good to me!

2025-04-24 14:42 UTC, merged